language: julia
os:
  - osx
  - linux
julia:
  - 0.7
notifications:
  email: false
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("Anasol"); Pkg.test("Anasol"; coverage=true)';
after_success:
  - julia -e 'import Pkg; import Anasol; cd(joinpath(dirname(pathof(Anasol)))) Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
